# This file is part of Requirements-Builder
# Copyright (C) 2015 CERN.
#
# Requirements-Builder is free software; you can redistribute it and/or
# modify it under the terms of the Revised BSD License; see LICENSE
# file for more details.

sudo: false

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

env:
  - REQUIREMENTS=devel
  - REQUIREMENTS=latest
  - REQUIREMENTS=lowest

cache:
  - pip

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install coveralls twine wheel"

install:
  - "travis_retry pip install -r requirements.${REQUIREMENTS}.txt"
  - "travis_retry pip install -e .[all]"

script: ./run-tests.sh

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: CHANGEME
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = latest
